var div0=document.createElement("div");
var div=document.createElement("div");
div0.appendChild(div);
div.setAttribute("class","split left");
var div1=document.createElement("div");
div1.setAttribute("class","centered")
div.appendChild(div1);
var form=document.createElement("form");
div1.appendChild(form);
var div3=document.createElement("div");
form.appendChild(div3);
div3.innerHTML="Name:";
var n=document.createElement("input");
n.setAttribute("type","text");
div3.appendChild(n);
var div2=document.createElement("div");
form.appendChild(div2);
div2.innerHTML="Email:";
var email=document.createElement("input");
email.setAttribute("type","text");
div2.appendChild(email);
var div4=document.createElement("div");
form.appendChild(div4);
div4.innerHTML="password:";
var pass=document.createElement("input");
pass.setAttribute("type","password");
div4.appendChild(pass);
var div5=document.createElement("div");
form.appendChild(div5);
div5.innerHTML="re-password:";
var repas=document.createElement("input");
repas.setAttribute("type","password");
div5.appendChild(repas);
var div6=document.createElement("div");
form.appendChild(div6);
div6.innerHTML="Country:"
var country=document.createElement("select");
div6.appendChild(country);
var op=document.createElement("option");
op.innerHTML="India";
country.appendChild(op);
var op1=document.createElement("option");
op1.innerHTML="England";
country.appendChild(op1);
var op2=document.createElement("option");
op2.innerHTML="America";
country.appendChild(op2);
var div7=document.createElement("div");
form.appendChild(div7);
div7.innerHTML="state";
var state=document.createElement("select");
div7.appendChild(state);
var op3=document.createElement("option");
op3.innerHTML="Tamil Nadu";
state.appendChild(op3);
var op4=document.createElement("option");
op4.innerHTML="Kerala";
state.appendChild(op4);
var op5=document.createElement("option");
op5.innerHTML="Delhi";
state.appendChild(op5);
var div8=document.createElement("div");
form.appendChild(div8);
div8.innerHTML="City";
var city=document.createElement("select");
div8.appendChild(city);
var op6=document.createElement("option");
op6.innerHTML="Chennai";
city.appendChild(op6);
var op7=document.createElement("option");
op7.innerHTML="Vellore";
city.appendChild(op7);
var op8=document.createElement("option");
op8.innerHTML="Tiruvallur";
city.appendChild(op8);
var div9=document.createElement("div");
form.appendChild(div9);
div9.innerHTML="Gender";
var div10=document.createElement("div");
div9.appendChild(div10);
var gender=document.createElement("input");
gender.setAttribute("type","radio");
gender.setAttribute("name","gender");
div10.innerHTML="Male";
var br=document.createElement("br");
div10.appendChild(gender);
var div11=document.createElement("div");
div9.appendChild(div11);
var gender1=document.createElement("input");
gender1.setAttribute("type","radio");
gender1.setAttribute("name","gender");
div11.innerHTML="Female";
div11.appendChild(gender1);
var div12=document.createElement("div");
div9.appendChild(div12);
var gender2=document.createElement("input");
gender2.setAttribute("type","radio");
gender2.setAttribute("name","gender");
div12.innerHTML="Other";
div12.appendChild(gender2);
var div13=document.createElement("div");
form.appendChild(div13);
div13.innerHTML="Marital Status";
var div14=document.createElement("div");
div13.appendChild(div14);
var ms=document.createElement("input");
ms.setAttribute("type","radio");
ms.setAttribute("name","ms");
div14.innerHTML="Single";
div14.appendChild(ms);
var div15=document.createElement("div");
div13.appendChild(div15);
var ms1=document.createElement("input");
ms1.setAttribute("type","radio");
ms1.setAttribute("name","ms");
div15.innerHTML="Married";
div15.appendChild(ms1);
var div16=document.createElement("div");
form.appendChild(div16);
div16.innerHTML="Fav places";
var div17=document.createElement("div");
div16.appendChild(div17);
var fav=document.createElement("input");
div17.innerHTML="Delhi";
fav.setAttribute("type","checkbox");
div17.appendChild(fav);
var div18=document.createElement("div");
div16.appendChild(div18);
var fav1=document.createElement("input");
div18.innerHTML="Mumbai";
fav1.setAttribute("type","checkbox");
div18.appendChild(fav1);
var div19=document.createElement("div");
div16.appendChild(div19);
var fav2=document.createElement("input");
div19.innerHTML="Chennai";
fav2.setAttribute("type","checkbox");
div19.appendChild(fav2);
var div20=document.createElement("div");
form.appendChild(div20);
var submit=document.createElement("input");
div20.appendChild(submit);
submit.setAttribute("type","button");
submit.setAttribute("value","submit");
submit.setAttribute("id","submit");
submit.setAttribute("style","color:red;justify-content: center");
submit.setAttribute("onclick","click()")



var div21=document.createElement("div");
div0.appendChild(div21);
div21.setAttribute("class","split right");
var div22=document.createElement("div");
div22.setAttribute("class","centered");
div21.appendChild(div22);
var table=document.createElement("table");
div22.appendChild(table);
var tr=document.createElement("tr");
table.appendChild(tr);
var th=document.createElement("th")
th.innerHTML="Name";
tr.appendChild(th);
var th1=document.createElement("th");
th1.innerHTML="Email";
tr.appendChild(th1);
var th2=document.createElement("th");
th2.innerHTML="Password";
tr.appendChild(th2);
var th3=document.createElement("th");
th3.innerHTML="Country";
tr.appendChild(th3);
var th4=document.createElement("th");
th4.innerHTML="State";
tr.appendChild(th4);
var th5=document.createElement("th");
th5.innerHTML="City";
tr.appendChild(th5);
var th6=document.createElement("th");
th6.innerHTML="Gender";
tr.appendChild(th6);
var th7=document.createElement("th");
th7.innerHTML="Marital Status";
tr.appendChild(th7);
var th8=document.createElement("th");
th8.innerHTML="Fav Places";
tr.appendChild(th8);
document.body.appendChild(table);
document.body.appendChild(div21);
document.body.appendChild(div0);

function click(){
    
}